# Generated by Django 4.0.3 on 2022-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name=models.CharField(max_length=50)),
            preserve_default=False,
        ),
    ]
